### ISSUE TITLE
四周目Mod预选

### ISSUE THREAD

**Issue by WakelessSloth56** [HaruhiFanClub/mcserver#1]
1. 此Issue用于四周目Mod的预选, 您可以在此提出建议或进行讨论.
1. 此处所列举的Mod仅作为预选列表, 正式版本将有较大出入.
1. 有新的Mod建议, 请在最后追加评论, 对某个评论中所列的Mod有问题的请回复对应评论.
1. 可以但没有必要列出前置类的Mod, 仅客户端Mod请不要在此提出, 仅服务端Mod请注明.
1. 使用如下格式进行新Mod提议(可以不按此格式自由发挥,无硬性要求,仅建议): 
`- [[模组主要特点或类型] 模组中文名称 (常用简称, 原始名称)](CurseForge项目链接,或原出处)`
例(实际显示见下方的评论):
`- [[生物群系] 超多生物群系 (BOP, Biomes O' Plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)`

**Comment by WakelessSloth56** [comment]
- [ ] 匠魂2 (Tinkers' Construct 2)
- [ ] 超多生物群系 (BOP, Biomes O' Plenty)

**Comment by WakelessSloth56** [comment]
- [[群系] 超多生物群系 (BOP, Biomes O' Plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
- [[实用] 匠魂2 (TiC2, Tinkers' Construct 2)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)

**Comment by WakelessSloth56** [comment]
- [[攻击] 背刺 (BackStab)](https://minecraft.curseforge.com/projects/backstab)
- [[生物强化] 圣化 (Consecration)](https://minecraft.curseforge.com/projects/consecration)
- [[生物强化] 史诗攻城 (Epic Siege)](https://minecraft.curseforge.com/projects/epic-siege-mod)
- [[冒险] 寻找巧克力重铸版 (CQR, Chocolate Quest Repoured)](https://www.curseforge.com/minecraft/mc-mods/cqrepoured)

**Comment by Libellule505** [comment]
- [[科技] 超能力/学园都市 (AC, AcademyCraft)](https://www.curseforge.com/minecraft/mc-mods/academycraft)
- [[科技] 科技枪 (TG, Techguns)](https://www.curseforge.com/minecraft/mc-mods/techguns)
- [[魔法] 星辉魔法 (AS, Astral Sorcery)](https://www.curseforge.com/minecraft/mc-mods/astral-sorcery)
- [[魔法] 巫术学 (Electroblob's Wizardry)](https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry)
- [[魔法] 魔法使 (Mahou Tsukai)](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai)
- [[冒险] 遗迹 (Ruins)](https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system)
- [[实用] 斯巴达的武器 (Spartan Weaponry)](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry)
- [[实用] 斯巴达之盾 (Spartan Shields)](https://www.curseforge.com/minecraft/mc-mods/spartan-shields)
- [[冒险] 阿图姆：沙漠之旅 (atum2,Atum 2: Return to the Sands)](https://www.curseforge.com/minecraft/mc-mods/atum)
- [[冒险] 圣遗物 (Reliquary)](https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3)
- [[生存修改] 难度调整 (Rough Tweaks)](https://www.curseforge.com/minecraft/mc-mods/rough-tweaks)
- [[实用] 传送石碑 (Waystones)](https://www.curseforge.com/minecraft/mc-mods/waystones)

**Comment by Libellule505** [comment]
- [[辅助] 时装盔甲重置版 (CAR, Cosmetic Armor Reworked)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)

**Comment by WakelessSloth56** [comment]
- [[装饰] MrCrayfish的家具 (MrCrayfish's Furniture Mod)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
- [[装饰] 凿子 (Chisel)](https://www.curseforge.com/minecraft/mc-mods/chisel)
- [[装饰] 雕凿工艺 (C&B, Chisels & Bits)](https://minecraft.curseforge.com/projects/chisels-bits)

**Comment by Libellule505** [comment]
- [[生物强化] 冠军 (Champions)](https://www.curseforge.com/minecraft/mc-mods/champions)
- [[实用] 随意作品 (RT,Ranbom Things)](https://www.curseforge.com/minecraft/mc-mods/random-things)

**Comment by WakelessSloth56** [comment]
- [[前置] CoFH核心 (CoFH Core)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
- [[前置] CoFH World](https://minecraft.curseforge.com/projects/cofh-world)
- [[科技] 热力基本 (TF, Thermal Foundation)](https://www.curseforge.com/minecraft/mc-mods/thermal-foundation)
- [[科技] 热力膨胀5 (TF5, Thermal Expansion 5)](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion)
- [[科技] 热动力学 (TD, Thermal Dynamics)](https://www.curseforge.com/minecraft/mc-mods/thermal-dynamics)
- [[科技] 热力革新 (TI, Thermal Innovation)](https://www.curseforge.com/minecraft/mc-mods/thermal-innovation)
- [[农业] 热力农业 (TC, Thermal Cultivation)](https://www.curseforge.com/minecraft/mc-mods/thermal-cultivation)

**Comment by WakelessSloth56** [comment]
- [[优化] Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
- [[手册] Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli)

**Comment by WakelessSloth56** [comment]
- [[自然生成] 气候控制/地理世界 (CC/GC, Climate Control/Geographicraft)](https://www.curseforge.com/minecraft/mc-mods/climate-control-geographicraft)
- [[自然生成] 真实地形生成 (RTG, Realistic Terrain Generation)](https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation)

**Comment by Libellule505** [comment]
- [[农业] 潘马斯农场 (Pam's HarvestCraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft)
- [[辅助] 更多潘马斯配方查询 (JEHC, Just Enough HarvestCraft)](https://www.curseforge.com/minecraft/mc-mods/just-enough-harvestcraft)
- [[生存修改] 动态潜行 (Dynamic Stealth)](https://www.curseforge.com/minecraft/mc-mods/dynamic-stealth)
- [[魔法] 妖术 (Bewitchment)](https://www.curseforge.com/minecraft/mc-mods/bewitchment)

**Comment by WakelessSloth56** [comment]
**预选已结束**
Mod列表见 ec7316e5728e1cc73212f0b99fecb223a43c8a85 的`server/minecraft/manifest.json`文件
