### ISSUE TITLE
[战利品表]向多个原版战利品表添加物品

### ISSUE THREAD

**Issue by Libellule505** [HaruhiFanClub/mcserver#10]
1. 添加物品：春日酱的眷顾。
      注：新id `god_bless_danchou_armband`  旧id`epic_reinforcement_stone`
2. 战利品箱子
<table border="1">
<tr><th>原版table名</th><th>抽取次数rolls</th><th>权重weight</th><th>品质quality</th><th>空权emptyweight</th></tr>
<tr><th>abandoned_mineshaft</th><th>1</th><th>1</th><th>1</th><th>23</th></tr>
<tr><th>bastion_hoglin_stable</th><th>1</th><th>2</th><th>1</th><th>27</th></tr>
<tr><th>bastion_other</th><th>1</th><th>4</th><th>1</th><th>95</th></tr>
<tr><th>bastion_treasure</th><th>3</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>buried_treasure</th><th>2</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>desert_pyramid</th><th>2</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>end_city_treasure</th><th>2</th><th>3</th><th>1</th><th>96</th></tr>
<tr><th>igloo_chest</th><th>6</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>jungle_temple</th><th>1</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>nether_bridge</th><th>2</th><th>2</th><th>2</th><th>96</th></tr>
<tr><th>pillager_outpost</th><th>1</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>ruined_portal</th><th>1</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>shipwreck_treasure</th><th>3</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>simple_dungeon</th><th>3</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>stronghold_corridor</th><th>4</th><th>3</th><th>1</th><th>96</th></tr>
<tr><th>underwater_ruin_big</th><th>3</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>underwater_ruin_small</th><th>1</th><th>1</th><th>1</th><th>14</th></tr>
<tr><th>woodland_mansion</th><th>3</th><th>1</th><th>1</th><th>14</th></tr>
</table>

3. 猪灵以物易物
<table border="1">
<tr><th>原版table名</th><th>抽取次数rolls</th><th>权重weight</th><th>品质quality</th><th>空权emptyweight</th></tr>
<tr><th>piglin_bartering</th><th>1</th><th>0</th><th>1</th><th>255</th></tr>
</table>

4. 钓鱼宝藏池
<table border="1">
<tr><th>原版table名</th><th>抽取次数rolls</th><th>权重weight</th><th>品质quality</th><th>空权emptyweight</th></tr>
<tr><th>treasure</th><th>1</th><th>1</th><th>0</th><th>127</th></tr>
</table>

**Comment by bgxd9592** [comment]
猪灵以物易物的无法使用quality：
猪灵以物易物创建的 `LootContext` 没有使用 `withLuck` 方法修改 `luck` 属性，即 `luck` 属性始为默认值0。

```java
# net.minecraft.entity.monster.piglin.PiglinTasks.getBarterResponseItems
private static List<ItemStack> getBarterResponseItems(PiglinEntity p_234524_0_) {
    LootTable loottable = p_234524_0_.level.getServer().getLootTables().get(LootTables.PIGLIN_BARTERING);
    return loottable.getRandomItems(
        (new LootContext.Builder((ServerWorld) p_234524_0_.level))
            .withParameter(LootParameters.THIS_ENTITY, p_234524_0_)
            .withRandom(p_234524_0_.level.random)
            .create(LootParameterSets.PIGLIN_BARTER)
    );
}
```

**Comment by Libellule505** [comment]
- 猪灵以物易物修改
<table border="1">
<tr><td>原版table名</td><td>抽取次数rolls</td><td>权重weight</td><td>品质quality</td><td>空权emptyweight</td></tr>
<tr><td>piglin_bartering</td><td>1</td><td>1</td><td>0</td><td>127</td></tr>
</table>

**Comment by Libellule505** [comment]
> 猪灵以物易物的无法使用quality：
> 猪灵以物易物创建的 `LootContext` 没有使用 `withLuck` 方法修改 `luck` 属性，即 `luck` 属性始为默认值0。
> 
> ```java
> # net.minecraft.entity.monster.piglin.PiglinTasks.getBarterResponseItems
> private static List<ItemStack> getBarterResponseItems(PiglinEntity p_234524_0_) {
>     LootTable loottable = p_234524_0_.level.getServer().getLootTables().get(LootTables.PIGLIN_BARTERING);
>     return loottable.getRandomItems(
>         (new LootContext.Builder((ServerWorld) p_234524_0_.level))
>             .withParameter(LootParameters.THIS_ENTITY, p_234524_0_)
>             .withRandom(p_234524_0_.level.random)
>             .create(LootParameterSets.PIGLIN_BARTER)
>     );
> }
> ```

   - 猪灵以物易物修改
<table border="1">
<tr><td>原版table名</td><td>抽取次数rolls</td><td>权重weight</td><td>品质quality</td><td>空权emptyweight</td></tr>
<tr><td>piglin_bartering</td><td>1</td><td>1</td><td>0</td><td>127</td></tr>
</table>
