### ISSUE TITLE
五周目Mod预选

### ISSUE THREAD

**Issue by WakelessSloth56** [HaruhiFanClub/mcserver#4]
1. 此议题用于 **五周目(V7)** 的 Mod 的预选，您可以在此提出建议或进行讨论。
1. 有新的 Mod 建议，请在最后追加评论；对某个评论中所列的 Mod 有问题的请回复对应评论。
    - 兼容性提醒：
        - Java版本：17
        - Minecraft版本：1.18.2
        - Forge版本：40.1.0
    -  除由 @AUIOC 或 @HaruhiFanClub 所开发的 Mod 外，**仅接受在 CurseForge 上存在的 Mod！**
1. 可以但没有必要列出前置类的 Mod；仅客户端Mod请不要在此提出，仅服务端Mod请注明。
1. 建议使用如下格式进行新 Mod 提议（可以不按此格式自由发挥，无硬性要求）：
`[[模组主要特点或类型] 模组中文名称 (常用简称, 原始名称)](CurseForge项目链接)`
    - 示例：
        - Markdown：`[[世界生成] 超多生物群系 (BOP, Biomes O' Plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)` 
        - 显示效果：[[世界生成] 超多生物群系 (BOP, Biomes O' Plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

**Comment by Libellule505** [comment]
[[实用-建设] 模拟殖民地 (MineColonies)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[[冒险-维度] 亚图姆：金沙之旅 (Atum2)](https://www.curseforge.com/minecraft/mc-mods/atum)
[[冒险-地牢/遗迹] 地牢+ (Dungeons Plus)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
[[冒险-地牢/遗迹] 飞行城堡 (Flying Castles)](https://www.curseforge.com/minecraft/mc-mods/flying-castles)
[[实用-物品] 圣遗物 (Reliquary)](https://www.curseforge.com/minecraft/mc-mods/reliquary-v1-3)
[[冒险-原版增补/改良] 碧海新生 (Upgrade Aquatic)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[[冒险-原版增补/改良] 刌民+ (Illagers+)](https://www.curseforge.com/minecraft/mc-mods/illagers)
[[魔法-死灵/黑魔法] Corail的墓碑 (Corail Tombstone)](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[[魔法-死灵/黑魔法] 幻梦 (Eidolon)](https://www.curseforge.com/minecraft/mc-mods/eidolon)
[[农业-种植] 潘马斯农场2-核心食物包 (Pam's HarvestCraft 2 - Food Core)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[[农业-种植] 潘马斯农场2-作物包 (Pam's HarvestCraft 2 - Crops)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[[农业-种植] 潘马斯农场2-树木包 (Pam's HarvestCraft 2 - Trees)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[[农业-种植] 潘马斯农场2-扩展食物包 (Pam's HarvestCraft 2 - Food Extended)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)
[[农业-季节/气候] 静谧四季 (Serene Seasons)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[[农业-生物/养殖] 无题鸭 (Untitled Duck)](https://www.curseforge.com/minecraft/mc-mods/untitled-duck-mod-forge)
[[农业-生物/养殖] 水产养殖2 (Aquaculture 2)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[[实用-物品] 弓箭手悖论 (Archers Paradox)](https://www.curseforge.com/minecraft/mc-mods/archers-paradox)
[[实用-附魔] 独特的附魔 (Unique Enchantments)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments)
[[实用-附魔] 独特的附魔：战斗扩展 (Unique Enchantments-Battle)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-battle)
[[实用-附魔] 独特的附魔：效用扩展 (Unique Enchantments-Utils)](https://www.curseforge.com/minecraft/mc-mods/unique-enchantments-utils)
[[实用-战利品] 战利品包 (Loot Bag Mod)](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod)
[[实用-原版增补/改良] 夸克 (Quark)](https://www.curseforge.com/minecraft/mc-mods/quark)
[[实用-交通] 小船 (Small Ships)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[[实用-物品] 地下城装备 (Dungeons Gear)](https://www.curseforge.com/minecraft/mc-mods/dungeons-gear)
[[冒险-怪物] 地下城生物 (Dungeons Mobs)](https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs)
[[冒险-难度] 冠军 (Champions)](https://www.curseforge.com/minecraft/mc-mods/champions)
[[冒险-难度] 怪物增强 (Improved Mobs)](https://www.curseforge.com/minecraft/mc-mods/improved-mobs)
[[世界生成] 超多生物群系 (BOP, Biomes O' Plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

**Comment by Libellule505** [comment]
[[冒险-难度] 着甲刌民 (Illagers Wear Armor)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)

**Comment by Haruhiyuki** [comment]
幻梦经测试可玩性有限，可考虑删除。Corail的墓碑有一些可能影响平衡性的内容，如[袪魔书](https://www.mcmod.cn/item/196462.html)，可考虑替换为更加纯净的墓碑mod，如[墓碑](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)。而魔法类内容的丰富，可考虑引入[[魔法-植物]植物魔法(Botania)](https://www.curseforge.com/minecraft/mc-mods/botania)，现在其高版本已较为成熟。[[魔法-植物]根源魔法经典版(Roots Classic)](https://www.curseforge.com/minecraft/mc-mods/roots-classic)也可以考虑引入，可以结合两者做一些魔改。

**Comment by Haruhiyuki** [comment]
[[冒险-战斗改良]挖矿与砍杀(Mine and Slash)](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded)可以提升战斗系统的可玩性与耐玩度，也让我们自定义对应难度的副本更有可行性。兼容上可能存在一定难度。

**Comment by Haruhiyuki** [comment]
[[辅助-建筑]创世神(WorldEdit)](https://www.curseforge.com/minecraft/mc-mods/worldedit)，可用于管理主城、副本、地形等。

**Comment by Haruhiyuki** [comment]
阿图姆的实际可游玩内容相对有限，可考虑更换更优秀的冒险维度mod，如[[冒险-维度]暮色森林(The Twilight Forest)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)。但更为建议的方案是，添加[[魔改]开放地形生成器(Open Terrain Generator)](https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator)，创建并维护一些多样的维度，如地牢/副本维度、PVP维度、小游戏维度、跑酷维度等。

**Comment by lainio24** [comment]
> 幻梦经测试可玩性有限，可考虑删除。Corail的墓碑有一些可能影响平衡性的内容，如[袪魔书](https://www.mcmod.cn/item/196462.html)，可考虑替换为更加纯净的墓碑mod，如[墓碑](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)。而魔法类内容的丰富，可考虑引入[[魔法-植物]植物魔法(Botania)](https://www.curseforge.com/minecraft/mc-mods/botania)，现在其高版本已较为成熟。[[魔法-植物]根源魔法经典版(Roots Classic)](https://www.curseforge.com/minecraft/mc-mods/roots-classic)也可以考虑引入，可以结合两者做一些魔改。

GraveStone Mod 容易出问题，经常性地找不到坟头或者压根就没有记录死亡，四周目的时候没少折磨管理去恢复玩家数据。
最终选择哪一个此类模组还需要进一步测试。

**Comment by lainio24** [comment]
> 阿图姆的实际可游玩内容相对有限，可考虑更换更优秀的冒险维度mod，如[[冒险-维度]暮色森林(The Twilight Forest)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)。但更为建议的方案是，添加[[魔改]开放地形生成器(Open Terrain Generator)](https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator)，创建并维护一些多样的维度，如地牢/副本维度、PVP维度、小游戏维度、跑酷维度等。

OTG 有考虑，但是出于性能考虑的话测试后大概率不会真的实装。

**Comment by Libellule505** [comment]
> [[冒险-战斗改良]挖矿与砍杀(Mine and Slash)](https://www.curseforge.com/minecraft/mc-mods/mine-and-slash-reloaded)可以提升战斗系统的可玩性与耐玩度，也让我们自定义对应难度的副本更有可行性。兼容上可能存在一定难度。

M&S会大幅度改变整体玩法，一般是纯RPG服会围绕M&S构建整合包甚至只加入单mod。

**Comment by Libellule505** [comment]
[[冒险-怪物]  (生物附魔, Enchant With Mob)](https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob)

**Comment by Libellule505** [comment]
移除部分mod：
[[实用-建设] 模拟殖民地 (MineColonies)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[[冒险-地牢/遗迹] 地牢+ (Dungeons Plus)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
[[冒险-地牢/遗迹] 飞行城堡 (Flying Castles)](https://www.curseforge.com/minecraft/mc-mods/flying-castles)
[[魔法-死灵/黑魔法] 幻梦 (Eidolon)](https://www.curseforge.com/minecraft/mc-mods/eidolon)

**Comment by Libellule505** [comment]
新增：
[[冒险-原版改良] YUNG的地牢优化 (YUNG's Better Dungeons)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
