### ISSUE TITLE
新增进度系统

### ISSUE THREAD

**Issue by Libellule505** [HaruhiFanClub/mcserver#5]
<table border="1">
  <tr>
    <th>图标</th><th>进度名</th><th>游戏内描述</th><th>上游进度</th><th>实际需求</th><th>id</th>
  </tr>
  <tr>
    <th>普通-团长袖标</th><th>让世界变得更热闹的凉宫春日的团！</th><th>获得团长身份的象征…之一。</th><th>-</th><th>在物品栏中获得团长袖标</th><th>sosdan/armband</th>
  </tr>
  <tr>
    <th>目标-附魔金剑</th><th>这合理吗？</th><th>心想事成，强化成功。</th><th>让世界变得更热闹的凉宫春日的团！</th><th>使用团长袖标强化成功。</th><th>sosdan/reinforcement</th>
  </tr>
 <tr>
    <th>目标-损坏的铁砧</th><th>哎呦似乎出了点问题</th><th>也许你还没得到团长的认可。</th><th>让世界变得更热闹的凉宫春日的团！</th><th>使用团长袖标强化失败。</th><th>sosdan/broken</th>
  </tr>
<tr>
    <th>普通-春日酱的眷顾</th><th>God bless</th><th>获得眷顾。</th><th>让世界变得更热闹的凉宫春日的团！</th><th>在物品栏中获得春日酱的眷顾。</th><th>sosdan/bless</th>
  </tr>
<tr>
    <th>挑战-团长立锥</th><th>God knows</th><th>只要她所希望的事，什么都能实现。</th><th>God bless</th><th>在物品栏中获得一件有30或以上等级附魔的物品。</th><th>sosdan/epic</th>
  </tr>
</table>

**Comment by Libellule505** [comment]
新增进度
<table border="1">
  <tr>
    <th>图标</th><th>进度名</th><th>游戏内描述</th><th>上游进度</th><th>实际需求</th><th>id</th>
  </tr>
  <tr>
    <th>普通-音乐唱片（in the summer time）</th><th>眷顾护体</th><th>获得眷顾的力量</th><th>God bless</th><th>在物品栏中获得一件需要用眷顾合成的物品。</th><th>sosdan/bless_gear</th>
  </tr>
  <tr>
    <th>目标-长门有希的魔法杖</th><th>宇宙人！</th><th>获得一整套宇宙人的装备。</th><th>眷顾护体</th><th>在物品栏中获得长门有希的魔法帽、长门有希的魔法斗篷和长门有希的魔法杖。</th><th>sosdan/alien</th>
  </tr>
  <tr>
    <th>目标-TPDD</th><th>未来人！</th><th>获得一整套未来人的装备</th><th>眷顾护体</th><th>在物品栏中获得朝比奈实玖瑠的女仆装、朝比奈实玖瑠的隐形眼镜和TPDD。</th><th>sosdan/future</th>
  </tr>
</table>

**Comment by Libellule505** [comment]
<table border="1">
<tr><th>图标</th><th>进度名</th><th>游戏内描述</th><th>上游进度</th><th>实际需求</th><th>id</th></tr>
<tr><th>目标-制导模式棒球棍</th><th>制导模式已开启</th><th>让长门同学对棒球棍吟唱咒语。</th><th>眷顾护体</th><th>在物品栏中获得制导模式棒球棍。</th><th>sosdan/bat</th></tr>
<tr><th>挑战-雪球</th><th>你哪来那么大力气？</th><th>真是的，乱来也要有个度啊</th><th>制导模式棒球棍</th><th>实际需求</th><th>sosdan/return_to_distance</th></tr>
</table>

**Comment by bgxd9592** [comment]
修改 ID 使其有更具体的含义

**Comment by Libellule505** [comment]
- God knows进度id改为legendary_equipment
   - 制导模式已开启进度id改为guided_mode
