### ISSUE TITLE
为HaruhiCore模组中的物品添加合成配方

### ISSUE THREAD

**Issue by bgxd9592** [HaruhiFanClub/mcserver#6]
- `haruhicore:wizard_hat` WakelessSloth56/haruhimod/issues/7
    - 工作台合成<table><tbody><tr><td>黑色羊毛</td><td>黑色羊毛</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>强化石</td><td>黑色羊毛</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
- `haruhicore:yukis_wizard_hat` WakelessSloth56/haruhimod/issues/8
    1. 工作台合成<table><tbody><tr><td>黑色羊毛</td><td>黑色羊毛</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>春日酱的眷顾</td><td>黑色羊毛</td></tr><tr><td>-</td><td>春日酱的眷顾</td><td>-</td></tr></tbody></table>
    1. 锻造台升级
        - 魔法帽 + 春日酱的眷顾

**Comment by bgxd9592** [comment]
- 音乐唱片无序合成 WakelessSloth56/haruhimod/issues/15
    - `haruhicore:music_disc_in_the_summertime` <table><tr><td>SOS团徽方块</td><td>春日酱的眷顾</td><td>蓝色染料</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></table>
    - `haruhicore:music_disc_someday_in_the_rain` <table><tr><td>SOS团徽方块</td><td>春日酱的眷顾</td><td>淡蓝色染料</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></table>
    - `haruhicore:music_disc_vox_in_box` <table><tr><td>SOS团徽方块</td><td>春日酱的眷顾</td><td>粉红色染料</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></table>
    - `haruhicore:music_disc_halo` <table><tr><td>SOS团徽方块</td><td>春日酱的眷顾</td><td>橙色染料</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></table>

**Comment by bgxd9592** [comment]
- `haruhicore:hourglass` WakelessSloth56/haruhimod/issues/18
    - 工作台合成 <table><tr><th>玻璃板</th><th>沙子</th><th>玻璃板</th></tr><tr><td>木棍</td><td>玻璃</td><td>木棍</td></tr><tr><th>玻璃板</th><th>沙子</th><th>玻璃板</th></tr></table>
- `haruhicore:tpdd` WakelessSloth56/haruhimod/issues/19
    - 工作台合成 <table><tr><th>玻璃板</th><th>沙子</th><th>玻璃板</th></tr><tr><td>春日酱的眷顾</td><td>玻璃</td><td>春日酱的眷顾</td></tr><tr><th>玻璃板</th><th>沙子</th><th>玻璃板</th></tr></table>

**Comment by bgxd9592** [comment]
- `haruhicore:wizard_cloak` WakelessSloth56/haruhimod/issues/9
    - 工作台合成<table><tbody><tr><td>黑色羊毛</td><td>强化石</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>黑色羊毛</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>黑色羊毛</td><td>黑色羊毛</td></tr></tbody></table>
- `haruhicore:yukis_wizard_cloak` WakelessSloth56/haruhimod/issues/10
    1. 工作台合成<table><tbody><tr><td>黑色羊毛</td><td>-</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>春日酱的眷顾</td><td>黑色羊毛</td></tr><tr><td>黑色羊毛</td><td>春日酱的眷顾</td><td>黑色羊毛</td></tr></tbody></table>
    2. 锻造台升级
        - 魔法斗篷 + 春日酱的眷顾

**Comment by bgxd9592** [comment]
- `haruhicore:maid_outfit` WakelessSloth56/haruhimod/issues/11
    - 工作台合成<table><tbody><tr><td>白色羊毛</td><td>强化石</td><td>白色羊毛</td></tr><tr><td>白色羊毛</td><td>白色羊毛</td><td>白色羊毛</td></tr><tr><td>白色羊毛</td><td>白色羊毛</td><td>白色羊毛</td></tr></tbody></table>
- `haruhicore:mikurus_maid_outfit` WakelessSloth56/haruhimod/issues/12
    1. 工作台合成<table><tbody><tr><td>白色羊毛</td><td>-</td><td>白色羊毛</td></tr><tr><td>白色羊毛</td><td>春日酱的眷顾</td><td>白色羊毛</td></tr><tr><td>白色羊毛</td><td>春日酱的眷顾</td><td>白色羊毛</td></tr></tbody></table>
    2. 锻造台升级
        - 女仆装 + 春日酱的眷顾

**Comment by bgxd9592** [comment]
- `haruhicore:danchou_cone`
    - 工作台合成 <table><tbody><tr><td>纸</td><td>黑色染料</td><td>纸</td></tr><tr><td>纸</td><td>白色染料</td><td>纸</td></tr><tr><td>纸</td><td>黑色染料</td><td>纸</td></tr></tbody></table>

**Comment by bgxd9592** [comment]
- `haruhicore:sos_badge_slab`
    - 工作台合成 <table><tbody><tr><td>羊毛</td><td>羊毛</td><td>羊毛</td></tr><tr><td>羊毛</td><td>羊毛</td><td>羊毛</td></tr><tr><td>羊毛</td><td>羊毛</td><td>羊毛</td></tr></tbody></table>

**Comment by bgxd9592** [comment]
- `haruhicore:reinforcement_stone` (`danchou_armband` WakelessSloth56/haruhimod/issues/3)
    - 工作台合成 <table><tbody><tr><td>锭</td><td>锭</td><td>锭</td></tr><tr><td>锭</td><td>青金石块</td><td>锭</td></tr><tr><td>锭</td><td>锭</td><td>锭</td></tr></tbody></table>

**Comment by bgxd9592** [comment]
https://github.com/HaruhiFanClub/MCHaruhiServer/issues/6#issuecomment-914127625 添加标签 所有锭(`haruhiserver:ingots`) 需要等待模组选定完成。暂定合成使用金锭。

**Comment by WakelessSloth56** [comment]
- `haruhicore:mikurus_contact` WakelessSloth56/haruhimod/issues/13
    - 无序合成<table><tbody><tr><td>蓝色染色玻璃板</td><td>春日酱的眷顾</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>

**Comment by WakelessSloth56** [comment]
- `haruhicore:baseball_bat` WakelessSloth56/haruhimod/issues/20
    - 工作台有序合成<table><tr><td>-</td><td>-</td><td>任意木板</td></tr><tr><td>-</td><td>任意木板</td><td>-</td></tr><tr><td>任意木板</td><td>-</td><td>-</td></tr></table>

- `haruhicore:guided_baseball_bat` WakelessSloth56/haruhimod/issues/21
    1. 工作台有序合成<table><tr><td>-</td><td>-</td><td>任意木板</td></tr><tr><td>春日酱的眷顾</td><td>任意木板</td><td>-</td></tr><tr><td>任意木板</td><td>春日酱的眷顾</td><td>-</td></tr></table>
    2. 锻造台升级
        - 棒球棍 + 春日酱的眷顾

**Comment by WakelessSloth56** [comment]
-  WakelessSloth56/haruhimod/issues/14
    - `haruhicore:inferior_wizard_wand`
        - 有序合成<table><tbody><tr><td>-</td><td>-</td><td>金锭</td></tr><tr><td>-</td><td>木棍</td><td>-</td></tr><tr><td>团长袖标</td><td>-</td><td>-</td></tr></tbody></table>
    - `haruhicore:ordinary_wizard_wand`
        -  无序合成<table><tbody><tr><td>魔法杖LV.1</td><td>团长袖标</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
    - `haruhicore:excellent_wizard_wand`
        -  无序合成<table><tbody><tr><td>魔法杖LV.2</td><td>钻石</td><td>钻石</td></tr><tr><td>钻石</td><td>钻石</td><td>钻石</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
    - `haruhicore:rare_wizard_wand`
        -  无序合成<table><tbody><tr><td>魔法杖LV.3</td><td>青金石块</td><td>青金石块</td></tr><tr><td>青金石块</td><td>青金石块</td><td>青金石块</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
    - `haruhicore:epic_wizard_wand`
        -  无序合成<table><tbody><tr><td>魔法杖LV.4</td><td>附魔之瓶</td><td>附魔之瓶</td></tr><tr><td>附魔之瓶</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
    - `haruhicore:yukis_wizard_wand`
        -  无序合成<table><tbody><tr><td>魔法杖LV.5</td><td>春日酱的眷顾</td><td>春日酱的眷顾</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></tbody></table>
